QT.qlyu_private.VERSION = 5.9.7
QT.qlyu_private.name = Qlyu
QT.qlyu_private.module =
QT.qlyu_private.libs = $$QT_MODULE_LIB_BASE
QT.qlyu_private.includes = $$QT_MODULE_INCLUDE_BASE/Qlyu/5.9.7 $$QT_MODULE_INCLUDE_BASE/Qlyu/5.9.7/Qlyu
QT.qlyu_private.frameworks =
QT.qlyu_private.depends = qlyu
QT.qlyu_private.uses =
QT.qlyu_private.module_config = v2 internal_module
QT.qlyu_private.enabled_features =
QT.qlyu_private.disabled_features =
