QT.qlyu.VERSION = 5.9.7
QT.qlyu.name = Qlyu
QT.qlyu.module = Qlyu
QT.qlyu.libs = $$QT_MODULE_LIB_BASE
QT.qlyu.includes = $$QT_MODULE_INCLUDE_BASE $$QT_MODULE_INCLUDE_BASE/Qlyu
QT.qlyu.frameworks =
QT.qlyu.bins = $$QT_MODULE_BIN_BASE
QT.qlyu.depends = core gui widgets
QT.qlyu.uses =
QT.qlyu.module_config = v2
QT.qlyu.DEFINES = QT_QLYU_LIB
QT.qlyu.enabled_features =
QT.qlyu.disabled_features =
QT_CONFIG +=
QT_MODULES += qlyu
